version: '3'

services: 
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g:latest
    ports:
      - 41521:1521
      - 45500:5500
      - 48080:8080
    volumes:
      - "./EXPORT_SCHEMAS:/u01/app/oracle/admin/XE/dpdump"